apiVersion: v1
kind: ConfigMap
metadata:
  name: syfosmarena-application-json
  namespace: default
  labels:
    team: teamsykefravr
data:
  application.json: |+
    {
      "mqHost": "a01apvl062.adeo.no",
      "mqPort": "1414",
      "mqQueueManager": "MPLSC03",
      "mqChannel": "P_SYFOSMARENA",
      "arenaQueue": "QA.P414.FS06_ARENA",
      "vaultURL" : "https://vault.adeo.no"
    }
